"""
license_keys_seed.py
Auto-generated, pre-issued license key pool: 50 Monthly + 50 Yearly keys.
Seeded into the license_keys table on first run (see database.py / init_db).

This is the SELLABLE inventory: SN Softech Solutions distributes one key
per customer/purchase. A key can only be activated once (enforced locally
by license.py). To issue more keys later, generate additional entries in
the same format (SNRE-MON-XXXX-XXXX / SNRE-YRL-XXXX-XXXX) and add them here
-- new keys added to this list are picked up automatically on next app start
(existing keys already in the database are left untouched).
"""

LICENSE_KEY_SEED = [
    # ---- Yearly Plan (365 days) — 50 keys ----
    ("SNRE-YRL-K8F9-PVKK", "Yearly"),
    ("SNRE-YRL-QB3K-PFQD", "Yearly"),
    ("SNRE-YRL-K4AA-68BG", "Yearly"),
    ("SNRE-YRL-BJUE-DQKG", "Yearly"),
    ("SNRE-YRL-K2ZX-URYH", "Yearly"),
    ("SNRE-YRL-675Z-FKC5", "Yearly"),
    ("SNRE-YRL-ESGY-QK3G", "Yearly"),
    ("SNRE-YRL-DAWF-42CM", "Yearly"),
    ("SNRE-YRL-G6KY-A5Q9", "Yearly"),
    ("SNRE-YRL-BK42-CYHD", "Yearly"),
    ("SNRE-YRL-5TZ4-TMUB", "Yearly"),
    ("SNRE-YRL-U4JP-36CY", "Yearly"),
    ("SNRE-YRL-BA2A-GE54", "Yearly"),
    ("SNRE-YRL-MB7N-QXQJ", "Yearly"),
    ("SNRE-YRL-HZ72-GWMF", "Yearly"),
    ("SNRE-YRL-6XE4-5VRM", "Yearly"),
    ("SNRE-YRL-NA98-HT8C", "Yearly"),
    ("SNRE-YRL-2QZS-C6V9", "Yearly"),
    ("SNRE-YRL-2RUH-48QU", "Yearly"),
    ("SNRE-YRL-GM3A-SYN8", "Yearly"),
    ("SNRE-YRL-FC88-YNPQ", "Yearly"),
    ("SNRE-YRL-4BUH-9BRT", "Yearly"),
    ("SNRE-YRL-6EBU-4U6A", "Yearly"),
    ("SNRE-YRL-G4SW-MDGC", "Yearly"),
    ("SNRE-YRL-XDFT-GU38", "Yearly"),
    ("SNRE-YRL-YWEN-XXQJ", "Yearly"),
    ("SNRE-YRL-YMN3-88VU", "Yearly"),
    ("SNRE-YRL-CN3J-NC9Z", "Yearly"),
    ("SNRE-YRL-G88H-GWA5", "Yearly"),
    ("SNRE-YRL-74U6-3W8Q", "Yearly"),
    ("SNRE-YRL-DWAJ-TSGM", "Yearly"),
    ("SNRE-YRL-6ZWP-PC3U", "Yearly"),
    ("SNRE-YRL-PABT-VCBT", "Yearly"),
    ("SNRE-YRL-9DYA-PGHM", "Yearly"),
    ("SNRE-YRL-4PFJ-ME78", "Yearly"),
    ("SNRE-YRL-89RX-8PFS", "Yearly"),
    ("SNRE-YRL-5TT3-WJXK", "Yearly"),
    ("SNRE-YRL-ATG7-CFMM", "Yearly"),
    ("SNRE-YRL-DC2R-WGVR", "Yearly"),
    ("SNRE-YRL-HRD9-TEWA", "Yearly"),
    ("SNRE-YRL-EDVN-ZJTJ", "Yearly"),
    ("SNRE-YRL-AVJD-HAJU", "Yearly"),
    ("SNRE-YRL-Q5HV-HURT", "Yearly"),
    ("SNRE-YRL-F4VR-8DRG", "Yearly"),
    ("SNRE-YRL-JFY3-VBMF", "Yearly"),
    ("SNRE-YRL-MKUF-HBN3", "Yearly"),
    ("SNRE-YRL-7SRN-CCTG", "Yearly"),
    ("SNRE-YRL-XVGW-XPVD", "Yearly"),
    ("SNRE-YRL-J64Z-FZW5", "Yearly"),
    ("SNRE-YRL-NJQF-9FVG", "Yearly"),
    # ---- Monthly Plan (30 days) — 50 keys ----
    ("SNRE-MON-8979-DVB7", "Monthly"),
    ("SNRE-MON-UB4T-X64A", "Monthly"),
    ("SNRE-MON-AQC5-APFJ", "Monthly"),
    ("SNRE-MON-UJ4G-WURH", "Monthly"),
    ("SNRE-MON-WUE6-GY5J", "Monthly"),
    ("SNRE-MON-QUAM-UDK8", "Monthly"),
    ("SNRE-MON-7EPY-YCB5", "Monthly"),
    ("SNRE-MON-ECN3-Q5PP", "Monthly"),
    ("SNRE-MON-3UTM-XKT5", "Monthly"),
    ("SNRE-MON-AVE7-K8FE", "Monthly"),
    ("SNRE-MON-TJRG-N8JV", "Monthly"),
    ("SNRE-MON-R8ZK-C2B3", "Monthly"),
    ("SNRE-MON-DB2H-5FXE", "Monthly"),
    ("SNRE-MON-REXJ-HUPB", "Monthly"),
    ("SNRE-MON-G6BY-3PEJ", "Monthly"),
    ("SNRE-MON-MWDG-A5YD", "Monthly"),
    ("SNRE-MON-AJ53-49W8", "Monthly"),
    ("SNRE-MON-H6WA-VFGP", "Monthly"),
    ("SNRE-MON-G62V-KSWG", "Monthly"),
    ("SNRE-MON-4HRP-UW3X", "Monthly"),
    ("SNRE-MON-FV3C-BUBV", "Monthly"),
    ("SNRE-MON-4MX6-RUKY", "Monthly"),
    ("SNRE-MON-NMW3-QDDU", "Monthly"),
    ("SNRE-MON-5SDV-STCE", "Monthly"),
    ("SNRE-MON-7XZX-97BJ", "Monthly"),
    ("SNRE-MON-4Z2N-UGUU", "Monthly"),
    ("SNRE-MON-N398-W8PX", "Monthly"),
    ("SNRE-MON-MCTB-J5JX", "Monthly"),
    ("SNRE-MON-3NPR-JV9J", "Monthly"),
    ("SNRE-MON-P9Y6-MN28", "Monthly"),
    ("SNRE-MON-FM55-CFP2", "Monthly"),
    ("SNRE-MON-4KU3-B9WZ", "Monthly"),
    ("SNRE-MON-6FRE-CXJS", "Monthly"),
    ("SNRE-MON-7XDE-TU4W", "Monthly"),
    ("SNRE-MON-8QQV-MX4N", "Monthly"),
    ("SNRE-MON-4GVZ-2FZ8", "Monthly"),
    ("SNRE-MON-62RC-PZKM", "Monthly"),
    ("SNRE-MON-R8TE-A34G", "Monthly"),
    ("SNRE-MON-YDAU-FYUK", "Monthly"),
    ("SNRE-MON-QMZK-ARTW", "Monthly"),
    ("SNRE-MON-TBMK-3YXS", "Monthly"),
    ("SNRE-MON-CKHR-A9PW", "Monthly"),
    ("SNRE-MON-BXUY-JAK9", "Monthly"),
    ("SNRE-MON-XCRA-PY9C", "Monthly"),
    ("SNRE-MON-FT8E-B8T6", "Monthly"),
    ("SNRE-MON-5GVN-DW9K", "Monthly"),
    ("SNRE-MON-N8VA-BBEX", "Monthly"),
    ("SNRE-MON-MV72-YG72", "Monthly"),
    ("SNRE-MON-U7AU-97PA", "Monthly"),
    ("SNRE-MON-4DDP-ZQXR", "Monthly"),
]
